### ISSUE TITLE
README issue

### ISSUE THREAD

**Issue by ji-one** [ji-one/algorithm-study#11]
링크 누르면 페이지가 안열린다 .... 🤔

**Comment by Dongwook9696** [comment]
마크다운 문법 미숙

**Comment by ji-one** [comment]
> 마크다운 문법 미숙

이게뭐얔ㅋㅋㅋㅋㅋㅋ이제봤다 너무하네~

**Comment by Dongwook9696** [comment]
오잉?? ㅋㅋㅋㅋㅋ 언제 했지
내가 안했다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by ji-one** [comment]
> 오잉?? ㅋㅋㅋㅋㅋ 언제 했지
> 내가 안했다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

엥 대놓고 황동욱 적혀잇구만 발뺌뭔뎈ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Dongwook9696** [comment]
그러네 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
미안합니다.
해결했다는게 중요한거 아니겠나 ☆★☆
